# AppStream data package
#
# This package ships pre-generated AppStream metadata for nixpkgs.
# The metadata is generated during development by running:
#   just generate
#
# The generation process correlates nixpkgs package metadata with Flathub's
# rich AppStream data (screenshots, descriptions, icons).
#
# To refresh the data:
#   1. just refresh   # Update nixpkgs-apps.json from local nixpkgs
#   2. just generate  # Re-correlate and generate appstream-data/
#   3. Commit the updated appstream-data/
{
  lib,
  stdenv,
}:
stdenv.mkDerivation {
  pname = "nixos-appstream-data";
  version = "1.0.0";

  # Pre-generated AppStream data
  src = ./appstream-data;

  dontBuild = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/share
    cp -r swcatalog $out/share/

    # Also provide legacy app-info location for compatibility
    mkdir -p $out/share/app-info
    if [ -d swcatalog/xml ]; then
      ln -s ../swcatalog/xml $out/share/app-info/xmls
    fi
    if [ -d swcatalog/icons ]; then
      ln -s ../swcatalog/icons $out/share/app-info/icons
    fi

    # Include the correlation report
    if [ -f correlation-report.json ]; then
      cp correlation-report.json $out/share/
    fi

    runHook postInstall
  '';

  meta = {
    description = "AppStream metadata for nixpkgs (generated via Flathub correlation)";
    longDescription = ''
      AppStream catalog for nixpkgs packages, generated by intelligently
      correlating nixpkgs package metadata with Flathub's rich AppStream data.

      This provides screenshots, descriptions, and icons for GUI applications
      in GNOME Software and KDE Discover without needing to build packages.

      The data is pre-generated during development and shipped as-is.
      To update, run `just refresh` then `just generate` in the dev environment.
    '';
    license = lib.licenses.mit;
    platforms = lib.platforms.linux;
    maintainers = [ ];
  };
}
